### PR TITLE
Initialize NetworkCredentials in EmailConnectionInfo

### LINKED ISSUE #90: Error during reading sink configuration from JSON file
Hi,
I encountered error during reading sink configuration from JSON file.

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=**Cannot create instance of type 'System.Net.ICredentialsByHost' because it is either abstract or an interface.**
>   Source=Microsoft.Extensions.Configuration.Binder

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Email" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Email",
        "Args": {
          "ConnectionInfo": {
            "NetworkCredentials": {
              "UserName": "username",
              "Password": "password"
            }
          }
        }
      }
    ]
  }
}
```
I wanted to use extension method with parameter `connectionInfo`.
https://github.com/serilog/serilog-sinks-email/blob/5fb82c6be87f40fb69e74fe301e57dac55cc6993/src/Serilog.Sinks.Email/LoggerConfigurationEmailExtensions.cs#L206-L214
It wont work, because constructor for `EmailConnectionInfo` class doesn't initialize new object for `NetworkCredentials` property.
https://github.com/serilog/serilog-sinks-email/blob/5fb82c6be87f40fb69e74fe301e57dac55cc6993/src/Serilog.Sinks.Email/Sinks/Email/EmailConnectionInfo.cs#L38-L48
I ended up writing custom extension method, but this issue looks like easy to fix.

### PR DESCRIPTION
**Pull request by adriangutowski**
Fixes #90

### CODE REVIEW

**Comment by adriangutowski** [comment]
@nblumhardt,
could you take a look at my PR?

**Comment by nblumhardt** [comment]
Thanks for the PR! I'm not sure whether this change will prevent the use of default credentials in environments that depend on them - unfortunately I'm short of time to investigate.

Any other maintainers currently following this repo with some bandwidth? :-)

**Comment by adriangutowski** [comment]
@nblumhardt,
thank you for your prompt reply. I did some research into this - and apparently it should not be an issue. Take a look at this: 
https://stackoverflow.com/a/14130274/7980221

**Comment by adriangutowski** [comment]
@nblumhardt,
how about setting the default value for `NetworkCredentials` to `CredentialCache.DefaultNetworkCredentials`? Could you take a look at my latest commit (26a2d4e1c0193bf4a237170b6b832f0ad4a86f99)?

**Comment by nblumhardt** [comment]
Sorry Adrian, I don't have any environment in which to test these things, so this has been sitting on my TODO list for a while. Can you share any details of what testing/investigation you've done? (E.g. why do you think this will preserve the existing behavior?)

Many thanks,
Nick

**Comment by nblumhardt** [comment]
Closing this one as stale, but thanks for sending the PR!

**Pull request closed without merging**
