### PR TITLE
Fix subtext in nuget package

### PR DESCRIPTION
**Pull request by LordMike**

### CODE REVIEW

**Comment by tsimbalar** [comment]
Hi Michael,

Thanks for you PR.

I think you can also use this PR to update the links to use HTTPS urls (Icon, Project, License) , and also change the project URL to point to this repo instead of the general serilog websites . 

(also I'm not sure keeping the tag `io` is releavant for the Email sink)

Cheers !

**Comment by LordMike** [comment]
Is this something that should be done for all Serilog projects?

**Comment by tsimbalar** [comment]
Well, we have started doing it at some point on some of the repos, but not on all of them yet (there's quite a lot !)... I think the idea was that nuget.org would show the README from the repos, but I don't see it happening . Any idea @nblumhardt  ?

**Comment by nblumhardt** [comment]
@tsimbalar it's coming, I believe - but at present it's necessary to paste the README text in via the NuGet.org web user interface :-)

**Comment by LordMike** [comment]
There must be a way to mass-manage these things.

**Comment by nblumhardt** [comment]
Sorry about the stall on this; closing as stale but appreciate the help! 👋

**Pull request closed without merging**
