### PR TITLE
Updated packages: Serilog 2.x, PeriodicBatching 2.x

### PR DESCRIPTION
**Pull request by michaelvolz**
Updated package to work with Asp.Net Core 1.0 RC2.

Please double check the changes in the build.ps1 file.

### CODE REVIEW

**Comment by michaelvolz** [comment]
Locally I just inserted a fixed version number like 2.0.0-rc2-1 into the `Serilog.Sinks.Email.nuspec` file and it worked. Any idea how to fix this properly?

`A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "Serilog [2.0.0-rc-556, )" or update the version field.`

**Comment by nblumhardt** [comment]
Hi Michael, thanks for the PR, much appreciated!

In the conversion to RC2 we're also switching how the build is performed, via the new `dotnet` tooling. It's still going to change between now and RTM, but it's currently the only way to get access to the .NET Core platform and builds on Mac/Linux.

The required changes (in this case for the _File_ sink) are in this diff: https://github.com/serilog/serilog-sinks-file/pull/1/files

Are you keen to take a shot at it with the new tooling? The experience is still, erm... "challenging" in parts, but the recipe in the linked PR (new _appveyor.yml_, simpler _Build.ps1_, project file and _project.json_ changes) should be perfect for this sink too.

**Comment by michaelvolz** [comment]
I will take a look. Thank you.

**Comment by michaelvolz** [comment]
Looks relatively straight forward, but there seems to be no x-plat mail support in .Net Core 1.0.
I'll investigate a little further.

**Comment by michaelvolz** [comment]
fyi: to temporarily fix the xunit test error in serilog.sinks.file you can use this suggestion: https://github.com/dotnet/cli/issues/3069#issuecomment-220005966
.
Worked on my machine :smile:

**Comment by michaelvolz** [comment]
@nblumhardt I am not sure if just copying the `appveyor.yml` without modification was the right move. Do we need to change the `secure: ... `section?

**Comment by michaelvolz** [comment]
This version is now transformed into the new projectsystem and supports `net4.5`.
To make it work with `netstandard1.3` we may need to depend on a third party solution for sending mails like `MailKit` 

 [Blog post about MailKit](http://stevejgordon.co.uk/how-to-send-emails-in-asp-net-core-1-0) 

Maybe you can give it a try and see if I forgot something?

**Comment by michaelvolz** [comment]
I think I will give MailKit a try.

**Comment by michaelvolz** [comment]
Showstopper for now: https://github.com/jstedfast/MailKit/issues/341

I need to wait until this bug is resolved to continue. @nblumhardt  arye you okay with me using MailKit?

**Comment by nblumhardt** [comment]
Great progress!

Regarding MailKit - sounds good, so long as we can scope the dependency to .NET Core, i.e. the code running on .NET 4.x can keep using System.Net.Mail.

The `"dependencies"` `project.json` element can be nested under the individual frameworks so this shouldn't be too much of a problem.

Sound like a plan?

**Comment by jstedfast** [comment]
A new MailKit has been published that supports RC2

**Comment by nblumhardt** [comment]
Thanks for the heads-up @jstedfast! :-)

**Comment by michaelvolz** [comment]
@nblumhardt do you have/know an existing sink with `net4x` and `netstandardx` to get some pointers?
Especially how to test them separately would be appreciated.

**Comment by nblumhardt** [comment]
Hi Michael - RollingFile https://github.com/serilog/serilog-sinks-rollingfile builds/tests against both platforms. The test project's `project.json` has everything needed - `dotnet test` takes care of multi-targeting so long as the test project declares each target. Let me know if you need more info. Cheers!

**Comment by adamchester** [comment]
Hi @michaelvolz do you still have plans to finish this?

**Comment by michaelvolz** [comment]
@adamchester No, I have no time.

**Comment by adamchester** [comment]
No probs, thanks!

**Pull request closed without merging**
