### PR TITLE
support config settings

### PR DESCRIPTION
**Pull request by stevenfirstrowinc**
I left the commented out code in so you could see what I was proposing.  Let me know your standards for commenting etc and I'll put those in too.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thank you Steven; the change looks good.

Couple of comments on the commits-

 - [ ] Removing the commented out lines would be good; GitHub displays changes as a diff anyway, so no trouble seeing what's going on
 - [ ] Something's up with the `EmailConnectionInfo.cs` file - is there a whitespace change in there? Seems to be showing all-deleted/all-added (see "Files changed" in the tabs above)
 - [ ] Rather than the internal `ToSmtpConnection` method going on the connection info class, can we please just move that to the `EmailSink` class? Will make following the code a little smoother, for very few additional lines

Cheers!
Nick

**Comment by stevenfirstrowinc** [comment]
ok I fixed the first and second items.  Please review.  As to the second one, I'm not sure why this happens.  We occasionally see this happen on our team.  Line endings maybe?

**Comment by nblumhardt** [comment]
Aaah... great catch. The serilog/serilog repository this came from has a .gitattributes file to determine line ending settings, which hasn't been carried over properly to the new sink repositories. I'll fix that now and move this change along ASAP. Thanks!

**Comment by nblumhardt** [comment]
Done, build should be on the way, thanks!

**Comment by stevenfirstrowinc** [comment]
awesome on time and budget!!  heh

**Pull request merged**
