### PR TITLE
Added NuGet restore configuration to project configuration

### PR DESCRIPTION
**Pull request by normanhh3**
Finally got a clean pull request and commit. :-)  I added this due to errors I saw in the Build.ps1 process calling the **nuget restore** command.  Figured this would at least help ensure that the dependencies are being pulled in properly.

### CODE REVIEW

**Comment by normanhh3** [comment]
AppVeyor check doesn't appear to have re-run with new changes, but it should build cleanly now.  Not sure if there is anything I can do to trigger that. :-/

**Comment by merbla** [comment]
hey @normanhh3 not sure this is needed.  I have seen Appveyor fail from time to time getting the packages however this seems transient.  Checkout [34](https://ci.appveyor.com/project/serilog/serilog-sinks-email/build/34) I think all is ok.  

Let me know your thoughts.

**Comment by normanhh3** [comment]
It really is a question of who you want to restore the packages. Do you want to be able to do it seamlessly from the project build when all you have is VS fired up?  At the moment you would have to pull in the deps via nuget restore as the Build.ps1 is doing.

This discussion though is why I thought it best to put it in its own PR. :-)

**Comment by merbla** [comment]
Sorry mate, I did not realise this change was for local dev not AppVeyor.  I am not sure we need to pull in the NuGet exe to do this.  I might check another couple of our sink repos & core to see how they achieve this.

**Comment by normanhh3** [comment]
Going to abandon this PR for now.  Looks like the project has moved on quite a bit from where my branch was, so I'm WAY out of sync at this point.

**Comment by nblumhardt** [comment]
Thanks @normanhh3

**Pull request closed without merging**
