### PR TITLE
Allow ITextFormatter and Is Email Body HTML override.

### PR DESCRIPTION
**Pull request by chrisbrain**
Added new overload to create EmailSink with custom ITextFormatter and added IsBodyHtml to EmailConnectionInfo.

These were to allow the full Serilog details to be written into the email, including the custom properties which had been added.

### CODE REVIEW

**Comment by merbla** [comment]
Thanks @chrisbrain looks good

**Comment by chrisbrain** [comment]
Great - Thanks.

**Comment by chrisbrain** [comment]
I don't think I created the pull request correctly sorry, this doesn't look right.

**Comment by chrisbrain** [comment]
Have had another go:
https://github.com/serilog/serilog-sinks-email/pull/7

I can actually see the changes I made this time.

**Pull request merged**
